<?php

namespace Cron\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Job
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Job extends EntityRepository
{
    /**
     * get completed cron jobs
     *
     * @return array of \Cron\Entity\Job
     */
    public function getHistory()
    {
        $dqb = $this->_em->createQueryBuilder();
        $dqb->select(array('j'))
            ->from('Cron\Entity\Job', 'j')
            ->where($dqb->expr()->in('j.status', array(
                'success', 'missed', 'error'
            )));
        return $dqb->getQuery()->getResult();
    }

    /**
     * get running cron jobs
     *
     * @return array of \Cron\Entity\Job
     */
    public function getRunning()
    {
        $dqb = $this->_em->createQueryBuilder();
        $dqb->select(array('j'))
            ->from('Cron\Entity\Job', 'j')
            ->where($dqb->expr()->in('j.status', array('running')));
        return $dqb->getQuery()->getResult();
    }
}
