<?php
// Auto-generated by Phing, using ZF2's classmap generator
// Generation time: Mon, 17 Sep 2012 21:33:50 +0800
return array(
    'Cron\Service\Cron'                       => __DIR__ . '/../Cron/Service/Cron.php',
    'Cron\Service\Registry'                   => __DIR__ . '/../Cron/Service/Registry.php',
    'Cron\Entity\Job'                         => __DIR__ . '/../Cron/Entity/Job.php',
    'Cron\Module'                             => __DIR__ . '/../Cron/Module.php',
    'Cron\Repository\Job'                     => __DIR__ . '/../Cron/Repository/Job.php',
    'Cron\Controller\CronController'          => __DIR__ . '/../Cron/Controller/CronController.php',
    'Cron\ExceptionInterface'                 => __DIR__ . '/../Cron/ExceptionInterface.php',
    'Cron\Exception\InvalidArgumentException' => __DIR__ . '/../Cron/Exception/InvalidArgumentException.php',
    'Cron\Exception\RuntimeException'         => __DIR__ . '/../Cron/Exception/RuntimeException.php',
);